In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [9]:
train_images = train_images / 255.0
test_images = test_images / 255.0

In [10]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4952 - accuracy: 0.8268
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3713 - accuracy: 0.8655
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3354 - accuracy: 0.8777
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3118 - accuracy: 0.8859
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2913 - accuracy: 0.8923


In [13]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 1ms/step - loss: 0.3511 - accuracy: 0.8773
Test accuracy: 0.8773000240325928


In [14]:
predictions = model.predict(test_images)

In [15]:
predictions[0]

array([1.8611423e-05, 4.2095922e-07, 9.5550956e-07, 5.0182184e-08,
       5.7248244e-06, 1.5842440e-03, 2.6654231e-04, 4.1196171e-02,
       4.9561759e-06, 9.5692235e-01], dtype=float32)

In [16]:
np.argmax(predictions[0])

9

In [17]:
test_labels[0]

9

In [18]:
img = test_images[0]
print(img.shape)

(28, 28)


In [ ]:
predictions_single = model.predict(img)
print(predictions_single)

In [ ]:
np.argmax(predictions_single[0])