In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [9]:
train_images = train_images / 255.0
test_images = test_images / 255.0

In [10]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.5033 - accuracy: 0.8228
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3763 - accuracy: 0.8649
Epoch 3/5
1875/1875 [==============================] - 2s 872us/step - loss: 0.3362 - accuracy: 0.8774
Epoch 4/5
1875/1875 [==============================] - 2s 886us/step - loss: 0.3115 - accuracy: 0.8866
Epoch 5/5
1875/1875 [==============================] - 2s 874us/step - loss: 0.2959 - accuracy: 0.8917


In [13]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 870us/step - loss: 0.3547 - accuracy: 0.8737
Test accuracy: 0.8737000226974487


In [14]:
predictions = model.predict(test_images)

In [15]:
predictions[0]

array([4.5442152e-07, 5.9056923e-08, 1.1188858e-07, 4.5960316e-09,
       3.3756925e-07, 4.0376056e-02, 4.9233654e-07, 6.1504249e-02,
       2.8247799e-05, 8.9809000e-01], dtype=float32)

In [16]:
np.argmax(predictions[0])

9

In [17]:
test_labels[0]

9

In [21]:
img = test_images[0]

print(img.shape)

(28, 28)


In [23]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 1, 28, 28)


In [24]:
predictions_single = model.predict(img)

print(predictions_single)

[[4.5442152e-07 5.9056923e-08 1.1188858e-07 4.5960227e-09 3.3756925e-07
  4.0376045e-02 4.9233654e-07 6.1504234e-02 2.8247796e-05 8.9809000e-01]]


In [25]:
np.argmax(predictions_single[0])

9